---

- name: install nginx using apt
  apt: name=nginx state=present

- name: replace default config with config for our demo application
  copy: src=default dest=/etc/nginx/sites-available/default mode=0644 

- name: start nginx service
  service: name=nginx state=started 

